package:
  name: mondrian_hmmcopy
  version: '0.7.0'

source:
  git_url: https://github.com/shahcompbio/mondrian.git
  git_rev: v0.7.0

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python
    - matplotlib
    - pandas=0.25.3
    - pypdf2
    - pypeliner
    - pysam
    - pyvcf
    - pyyaml
    - seaborn
    - statsmodels
    - scikit-learn
    - ete3
    - bioconductor-hmmcopy-single-cell
about:
  home: http://shahlab.ca
  summary: 'Bioinformatics pipeline for single cell analysis'

