package:
  name: mondrian_annotation
  version: '0.7.0'
source:
  git_url: https://github.com/shahcompbio/mondrian.git
  git_rev: v0.7.0
build:
  number: 1
requirements:
  build:
    - python
  run:
    - python
    - matplotlib
    - pandas=0.25.3
    - pypdf2
    - pypeliner
    - pyyaml
    - seaborn
    - statsmodels
    - scikit-learn
    - pytables
    - ete3
    - cell_cycle_classifier=0.0.2
    - click
    - jinja2
about:
  home: http://shahlab.ca
  summary: 'Bioinformatics pipeline for single cell analysis'
